spring.application.name=server
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sapphire}
spring.datasource.username=${DB_USERNAME:sapphire}
spring.datasource.password=${DB_PASSWORD:sapphire}
spring.datasource.driver-class-name=org.postgresql.Driver
